/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <lcm/lcm_coretypes.h>

#ifndef __uav_traject_uav_traject_t_hpp__
#define __uav_traject_uav_traject_t_hpp__

#include <vector>

namespace uav_traject
{

class uav_traject_t
{
    public:
        int64_t    timestamp;

        int8_t     num_keyframe;

        int8_t     order_p_1;

        std::vector< double > t;

        std::vector< std::vector< std::vector< double > > > traject;

    public:
        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void *buf, int offset, int maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline int getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to reqad while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void *buf, int offset, int maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "uav_traject_t"
         */
        inline static const char* getTypeName();

        // LCM support functions. Users should not call these
        inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
        inline int _getEncodedSizeNoHash() const;
        inline int _decodeNoHash(const void *buf, int offset, int maxlen);
        inline static uint64_t _computeHash(const __lcm_hash_ptr *p);
};

int uav_traject_t::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = (int64_t)getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int uav_traject_t::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int uav_traject_t::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t uav_traject_t::getHash()
{
    static int64_t hash = _computeHash(NULL);
    return hash;
}

const char* uav_traject_t::getTypeName()
{
    return "uav_traject_t";
}

int uav_traject_t::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &this->timestamp, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, &this->num_keyframe, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, &this->order_p_1, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->num_keyframe > 0) {
        tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->t[0], this->num_keyframe);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    for (int a0 = 0; a0 < this->num_keyframe; a0++) {
        for (int a1 = 0; a1 < this->order_p_1; a1++) {
            tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->traject[a0][a1][0], 4);
            if(tlen < 0) return tlen; else pos += tlen;
        }
    }

    return pos;
}

int uav_traject_t::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    tlen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this->timestamp, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, &this->num_keyframe, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, &this->order_p_1, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->num_keyframe) {
        this->t.resize(this->num_keyframe);
        tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->t[0], this->num_keyframe);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    this->traject.resize(this->num_keyframe);
    for (int a0 = 0; a0 < this->num_keyframe; a0++) {
        this->traject[a0].resize(this->order_p_1);
        for (int a1 = 0; a1 < this->order_p_1; a1++) {
            if(4) {
                this->traject[a0][a1].resize(4);
                tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->traject[a0][a1][0], 4);
                if(tlen < 0) return tlen; else pos += tlen;
            }
        }
    }

    return pos;
}

int uav_traject_t::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += __int64_t_encoded_array_size(NULL, 1);
    enc_size += __int8_t_encoded_array_size(NULL, 1);
    enc_size += __int8_t_encoded_array_size(NULL, 1);
    enc_size += __double_encoded_array_size(NULL, this->num_keyframe);
    enc_size += this->num_keyframe * this->order_p_1 * __double_encoded_array_size(NULL, 4);
    return enc_size;
}

uint64_t uav_traject_t::_computeHash(const __lcm_hash_ptr *)
{
    uint64_t hash = 0x54c0ef43ff70018aLL;
    return (hash<<1) + ((hash>>63)&1);
}

}

#endif
